FROM tendermint/tendermint:latest as tendermint

WORKDIR /var/www/tendermint
RUN tendermint init

FROM golang:1.14-alpine as ledger-node

WORKDIR /ledger-node

COPY /proof-of-concept/ledger-node /ledger-node
COPY --from=tendermint /var/www/tendermint /ledger-node/data

COPY tendermint-config.toml /ledger-node/data/config/config.toml

RUN go build

ENTRYPOINT [ "./ledger-node" ]-v "$(pwd)/tendermint:/tendermint:Z"